[package]
name = "crack-core"
version = "0.3.0"
authors = ["Cycle Five <cycle.five@proton.me>"]
edition = "2021"
description = "Core module for the cracking smoking, discord-music-bot Cracktunes."
publish = true
license = "MIT"
keywords = ["music", "discord", "bot", "crack", "tunes"]
categories = ["multimedia::audio"]
homepage = "https://cracktun.es/"
repository = "https://git.sr.ht/~cycle-five/cracktunes"


[features]
default = ["cache", "playlist", "crack-gpt", "crack-osint"]
playlist = []
shuttle = []
log_all = []
cache = ["serenity/cache", "poise/cache"]
crack-metrics = ["prometheus"]
crack-gpt = ["dep:crack-gpt"]
crack-osint = ["dep:crack-osint"]

[dependencies]
audiopus = "0.3.0-rc.0"
async-trait = "0.1"
colored = "2.1"
lazy_static = "1.4"
lyric_finder = "0.1"
rand = "0.8"
regex = "1.10"
serde_json = "1.0"
serde_with = "3.7"
url = "2.5"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_stream = { version = "1.0", features = ["tokio"] }
sys-info = "0.9"
prometheus = { version = "0.13", features = ["process"], optional = true }
anyhow = "1.0"
proc-macro2 = "1.0"
typemap_rev = "0.3"
chatgpt_rs = "1.2"
either = "1.10"
chrono = { version = "0.4", features = ["serde"] }
crack-gpt = { path = "../crack-gpt", optional = true }
crack-osint = { path = "../crack-osint", optional = true }
tracing = { workspace = true }
reqwest = { workspace = true }
sqlx = { workspace = true, optional = true }
serenity = { workspace = true }
songbird = { workspace = true }
symphonia = { workspace = true }
tokio = { workspace = true }
poise = { workspace = true }
tungstenite = { workspace = true }
async-tungstenite = { workspace = true }

[dependencies.rspotify]
git = "https://github.com/cycle-five/rspotify"
branch = "no-oldtime"

# To get additional codecs, you *must* add Symphonia yourself.
# # This includes the default formats (MKV/WebM, Ogg, Wave) and codecs (FLAC, PCM, Vorbis)...
# [dependencies.symphonia]
# version = "0.5.3"
# features = ["all"]

[dependencies.ffprobe]
git = "https://github.com/cycle-five/ffprobe-rs"

[dev-dependencies]
mockall = "0.12"
tungstenite = "0.21"
async-tungstenite = "0.25"
