[package]
name = "crack-core"
version = "0.2.15"
authors = ["Cycle Five <cycle.five@proton.me>"]
edition = "2021"
description = "A Discord music bot built on Rust and Crack."
repository = "https://github.com/cycle-five/cracktunes"
license = "MIT"
keywords = ["discord", "music-bot", "rust"]

[features]
default = ["playlist", "crack-gpt"]
playlist = []
shuttle = []
log_all = []
crack-gpt = []

[dependencies]
audiopus = "0.3.0-rc.0"
async-trait = "0.1"
colored = "2.0"
lazy_static = "1.4"
lyric_finder = "0.1"
rand = "0.8"
regex = "1.10"
serde_json = "1.0"
url = "2.4"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_stream = { version = "1.0", features = ["tokio"] }
sys-info = "0.9"
prometheus = { version = "0.13", features = ["process"] }
anyhow = "1.0"
proc-macro2 = "1.0"
typemap_rev = "0.3"
chatgpt_rs = "1.2"
chrono = "0.4"
crack-gpt = { path = "../crack-gpt" }
tracing = { workspace = true }
reqwest = { workspace = true }
sqlx = { workspace = true, optional = true }
serenity = { workspace = true }
songbird = { workspace = true }
symphonia = { workspace = true }
tokio = { workspace = true }
poise = { workspace = true }
tungstenite = { workspace = true }
async-tungstenite = { workspace = true }

[dependencies.rspotify]
git = "https://github.com/cycle-five/rspotify"
branch = "no-oldtime"

# To get additional codecs, you *must* add Symphonia yourself.
# # This includes the default formats (MKV/WebM, Ogg, Wave) and codecs (FLAC, PCM, Vorbis)...
# [dependencies.symphonia]
# version = "0.5.3"
# features = ["all"]

[dependencies.ffprobe]
git = "https://github.com/cycle-five/ffprobe-rs"

[dev-dependencies]
tungstenite = "^0.20.1"
async-tungstenite = "^0.23.0"
mockall = "0.11.4"
