[package]
name = "crack-core"
version = "0.3.7"
authors = ["Cycle Five <cycle.five@proton.me>"]
edition = "2021"
description = "Core module for the cracking smoking, discord-music-bot Cracktunes."
publish = true
license = "MIT"
keywords = ["music", "discord", "bot", "crack", "tunes", "cracktunes"]
categories = ["multimedia::audio"]
homepage = "https://cracktun.es/"
repository = "https://git.sr.ht/~cycle-five/cracktunes"


[features]
default = ["cache", "playlist", "ignore-presence-log"]
playlist = []
shuttle = []
ignore-presence-log = []
cache = ["serenity/cache", "poise/cache"]
crack-metrics = ["prometheus"]
crack-gpt = ["dep:crack-gpt"]
crack-osint = ["dep:crack-osint"]

[dependencies]
rusty_ytdl = { git = "https://github.com/cycle-five/rusty_ytdl", default-features = false, branch = "v0.7.2-boa", features = [
    "live",
    "rustls-tls",
    "search",
    "blocking",
    "ffmpeg",
] }
audiopus = "0.3.0-rc.0"
async-trait = "0.1.80"
anyhow = "1.0.83"
bytes = "1.6.0"
colored = "2.1.0"
lazy_static = "1.4.0"
lyric_finder = { git = "https://github.com/cycle-five/spotify-player", branch = "master", version = "0.1.6" }
rand = "0.8.5"
regex = "1.10.4"
serde = { version = "1.0.202", features = ["derive", "rc"] }
serde_json = "1.0.117"
serde_with = "3.8.1"
url = "2.5.0"
sys-info = "0.9.1"
prometheus = { version = "0.13.4", features = ["process"], optional = true }
proc-macro2 = "1.0.82"
typemap_rev = "0.3.0"
chatgpt_rs = { git = "https://github.com/cycle-five/chatgpt_rs", version = "1.2.4", branch = "master", optional = true }
either = "1.11.0"
chrono = { version = "0.4.38", features = ["serde"] }
once_cell = "1.19.0"
reqwest = { version = "0.12.4", default-features = false, features = [
    "blocking",
    "json",
    "multipart",
    "rustls-tls",
    "cookies",
] }

crack-gpt = { path = "../crack-gpt", optional = true }
crack-osint = { path = "../crack-osint", optional = true }
tracing = { workspace = true }
sqlx = { workspace = true }
serenity = { workspace = true }
songbird = { workspace = true }
tokio = { workspace = true }
poise = { workspace = true }

[dependencies.symphonia]
version = "0.5.4"
# features = ["all-formats", "all-codecs", "opt-simd"]
features = ["aac", "mp3", "isomp4", "alac"]

[dependencies.serenity-voice-model]
version = "0.2.0"

[dependencies.rspotify]
version = "0.13.1"
default-features = false
features = ["client-reqwest", "reqwest-rustls-tls"]

[dependencies.ffprobe]
git = "https://github.com/cycle-five/ffprobe-rs"
features = ["async-tokio"]
version = "0.4.0"

[dev-dependencies]
ctor = "0.2.8"
mockall = "0.12.1"
tungstenite = "0.21.0"
async-tungstenite = "0.25.1"
sqlx = { version = "0.7.4", features = [
    "runtime-tokio",
    "tls-rustls",
    "macros",
    "postgres",
    "chrono",
    "time",
    "migrate",
    "json",
] }
