image: debian/bookworm
secrets:
      - 5ec53080-dbed-4207-ab0f-d6056a62bb46
tasks:
      - install-dependencies: |
              sudo apt-get update
              sudo apt-get install -y \
                autoconf \
                automake \
                cmake \
                libtool \
                libssl-dev \
                pkg-config \
                gcc g++ \
                curl \
                libopus-dev \
                git
              sudo apt-get autoremove -y
              sudo apt-get clean -y
              sudo rm -rf /var/lib/apt/lists/*
      - install-rust: |
              curl -proto '=https' -tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
              . "$HOME/.cargo/env"
              rustup install nightly
              rustup default nightly
      #   - install-tarpaulin: |
      #       . "$HOME/.cargo/env"
      #       cargo install cargo-tarpaulin
      - install-yt-dlp: |
              sudo curl -sSL --output /usr/local/bin/yt-dlp https://github.com/yt-dlp/yt-dlp-master-builds/releases/download/2024.03.10.193100/yt-dlp_linux 
              sudo chmod +x /usr/local/bin/yt-dlp

      - fmt: |
              export DATABASE_URL=XXX
              . "$HOME/.cargo/env"
              cd cracktunes
              cargo +nightly fmt --all -- --check
      - lint: |
              export DATABASE_URL=XXX
              . "$HOME/.cargo/env"
              cd cracktunes
              cargo +nightly clippy --all-features --all -- -D clippy::all -D warnings
      - test: |
              export VIRUSTOTAL_API_KEY=$(cat ~/VIRUSTOTAL_API_KEY)
              export DATABASE_URL=XXX
              . "$HOME/.cargo/env"
              cd cracktunes
              # cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
              cargo +nightly test
