image: debian/bookworm
tasks:
  - install-dependencies: |
      sudo apt-get update -y
      sudo apt-get install -y \
        autoconf \
        automake \
        cmake \
        libtool \
        libssl-dev \
        pkg-config \
        gcc g++ \
        curl \
        libopus-dev
      sudo apt-get autoremove -y
      sudo apt-get clean -y
      sudo rm -rf /var/lib/apt/lists/*
  - install-rust: |
      curl -proto '=https' -tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      . "$HOME/.cargo/env"
      rustup install nightly
      rustup default nightly
  - fmt: |
      . "$HOME/.cargo/env"
      cd cracktunes
      cargo +nightly fmt --all -- --check
  - lint: |
      . "$HOME/.cargo/env"
      cd cracktunes
      cargo +nightly clippy --all -- -D warnings
  - test: |
      . "$HOME/.cargo/env"
      cd cracktunes
      # cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      cargo test
