fn main() -> Result<(), Box<dyn std::error::Error>> {
    // For the githash of the build
    vergen::EmitBuilder::builder()
        .all_build()
        .all_git()
        .emit()?;
    // make sure tarpaulin is included in the build
    println!("cargo:rustc-check-cfg=cfg(tarpaulin_include)");
    // generated by `sqlx migrate build-script`
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    Ok(())
}
