[workspace]
members = ["cracktunes", "crack-core", "crack-osint", "crack-gpt"]
resolver = "2"

[workspace.dependencies]
crack-core = { path = "crack-core", default-features = true, version = "0.2.16" }
crack-osint = { path = "crack-osint", default-features = true, version = "0.1" }
crack-gpt = { path = "crack-gpt", default-features = true, version = "0.1" }
tungstenite = "0.21"
async-tungstenite = "0.24"
reqwest = { version = "0.11", features = ["blocking", "json"] }
audiopus = "0.3.0-rc.0"
either = "1.9"
opentelemetry = { version = "0.21" }
opentelemetry-otlp = { version = "0.14" }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
opentelemetry-semantic-conventions = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.5", features = ["request-id"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-futures = "0.2"
tracing-opentelemetry = "0.22"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-bunyan-formatter = "0.3"
uuid = "1.7"


[workspace.dependencies.sqlx]
version = "0.7.3"
default-features = false
features = [
  "runtime-tokio",
  "tls-rustls",
  "macros",
  "postgres",
  "chrono",
  "time",
  "migrate",
  "json",
]

[workspace.dependencies.serenity]
#version = "0.12.0-rc2"
version = "0.12.0"
# git = "https://github.com/serenity-rs/serenity"
# branch = "next"
default-features = false
features = [
  "builder",
  "cache",
  "temp_cache",
  "collector",
  "client",
  "framework",
  "http",
  "standard_framework",
  "gateway",
  "model",
  "utils",
  "rustls_backend",
  "unstable_discord_api",
  "voice",
]

[workspace.dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
version = "0.4.0"
features = ["driver", "serenity", "rustls", "receive", "builtin-queue"]


# To get additional codecs, you *must* add Symphonia yourself.
# This includes the default formats (MKV/WebM, Ogg, Wave) and codecs (FLAC, PCM, Vorbis)...
[workspace.dependencies.symphonia]
version = "0.5.3"
default-features = false
features = ["all"]

[workspace.dependencies.poise]
# version = "0.5.6"
# version = "0.5.5"
# path = "../poise"
git = "https://github.com/cycle-five/poise"
branch = "current"
# git = "https://github.com/serenity-rs/poise"
# branch = "serenity-next"
# path = "../../src/poise"
default-features = true
features = ["cache", "chrono", "handle_panics"]

[workspace.dependencies.tokio]
version = "1.35"
features = ["macros", "rt-multi-thread", "signal"]

[profile.release-with-debug]
inherits = "release"
debug = true
