[workspace]
members = [
    "cracktunes",
    "crack-core",
    "crack-osint",
    "crack-config",
    "crack-gpt"
]
resolver = "2"

[workspace.dependencies]
crack-core = { path = "crack-core", default-features = true, version = "0.2.11" }
crack-osint = { path = "crack-osint", default-features = true, version = "0.1.0" }
crack-config = { path = "crack-config", default-features = true, version = "0.1.0" }
crack-gpt = { path = "crack-gpt", default-features = true, version = "0.1.0" }
tungstenite = "^0.20.1"
async-tungstenite = "^0.23.0"
reqwest = {version = "0.11.22", features = ["blocking", "json"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[workspace.dependencies.sqlx]
version = "0.7.2"
default-features = false
features = [
  "runtime-tokio",
  "tls-rustls",
  "macros",
  "sqlite",
  "postgres",
  "chrono",
  "migrate",
]

[workspace.dependencies.serenity]
version = "0.11.6"
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = [
  "builder",
  "cache",
  "collector",
  "client",
  "gateway",
  "temp_cache",
  "model",
  "utils",
  "rustls_backend",
  "unstable_discord_api",
  "voice",
]

[workspace.dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "next"
# version = "0.4"
features = [
  "driver",
  "rustls",
  "serenity",
  "builtin-queue",
]


# To get additional codecs, you *must* add Symphonia yourself.
# This includes the default formats (MKV/WebM, Ogg, Wave) and codecs (FLAC, PCM, Vorbis)...
[workspace.dependencies.symphonia]
version = "0.5.3"
features = ["aac", "mp3", "isomp4", "alac"] # ...as well as any extras you need!

[workspace.dependencies.poise]
# version = "0.5.6"
git = "https://github.com/cycle-five/poise"
branch = "serenity-next"
default-features = true

[workspace.dependencies.tokio]
version = "1.33.0"
features = ["macros", "rt-multi-thread", "signal"]

[profile.release-with-debug]
inherits = "release"
debug = true