[workspace]
members = [
    "cracktunes",
    "crack-core",
    "crack-osint",
    "crack-config",
]
resolver = "2"

[workspace.dependencies]
crack-core = { path = "crack-core", default-features = true, version = "0.2.9" }
crack-osint = { path = "crack-osint", default-features = true, version = "0.1.0" }
crack-config = { path = "crack-config", default-features = true, version = "0.1.0" }
tungstenite = "0.20.1"
reqwest = {version = "0.11.22", features = ["blocking", "json"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[workspace.dependencies.sqlx]
version = "0.7.2"
default-features = false
features = [
#  "runtime-tokio",
  "tls-rustls",
  "macros",
  "sqlite",
  "postgres",
  "chrono",
  "migrate",
]

[workspace.dependencies.serenity]
version = "0.11.6"
default-features = false
features = [
  "builder",
  "cache",
  "collector",
  "client",
  "gateway",
  "temp_cache",
  "model",
  "utils",
  "rustls_backend",
  "unstable_discord_api",
  "voice",
]

[workspace.dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
version = "0.3.2"
features = [
  "driver-core",
  "driver",
  "rustls",
  "serenity",
  "builtin-queue",
  "yt-dlp",
  "audiopus",
]

[workspace.dependencies.poise]
version = "0.5.6"
default-features = true

[workspace.dependencies.tokio]
version = "1.33.0"
features = ["macros", "rt-multi-thread", "signal"]

[workspace.dev-dependencies]
tungstenite = "0.20.1"