[package]
name = "cracktunes"
version = "0.2.1"
authors = ["Cycle Five <cycle.five@proton.me>", "aquelemiguel"]
edition = "2018"
description = "A Discord music bot built on Rust and Crack."
repository = "https://github.com/cycle-five/cracktunes"
license = "MIT"
keywords = ["discord", "music-bot", "rust"]

[dependencies]
audiopus = "0.2.0"
ctrlc = "3.4.0"
chatgpt_rs = "1.1.10"
colored = "2.0.0"
dotenv = "0.15.0"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.8.4"
rspotify = "0.11.7"
serde_json = "1.0.99"
url = "2.4.0"
serde = { version = "1.0.164", features = ["derive", "rc"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
sys-info = "0.9.1"
chrono = "0.4.26"
config-file = {version="0.2.3", features =["json"]}
reqwest = { version = "0.11.18", features = ["json"] }
date_time_parser = "0.1.0"

[dependencies.songbird]
version = "0.3.2"
features = [
  "driver-core",
  "driver",
  "rustls",
  "serenity",
  "builtin-queue",
  "yt-dlp",
  "audiopus",
]

[dependencies.serenity]
version = "0.11.6"
default-features = false
features = [
  "builder",
  "cache",
  "collector",
  "client",
  "gateway",
  "temp_cache",
  "model",
  "utils",
  "rustls_backend",
  "unstable_discord_api",
  "voice",
]

[dependencies.poise]
version = "0.5.5"
default-features = true

[dependencies.tokio]
version = "1.29.0"
features = ["macros", "rt-multi-thread", "signal"]

[dependencies.ffprobe]
git = "https://github.com/cycle-five/ffprobe-rs"
