[workspace]
members = ["cracktunes", "crack-core", "crack-osint", "crack-gpt"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Cycle Five <cycle.five@proton.me>"]


[workspace.dependencies]
crack-core = { path = "crack-core", default-features = true, version = "0.3.2" }
crack-osint = { path = "crack-osint", default-features = true, version = "0.1" }
crack-gpt = { path = "crack-gpt", default-features = true, version = "0.1" }

reqwest = { version = "0.11", features = ["blocking", "json", "multipart"] }
audiopus = "0.3.0-rc.0"
either = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
uuid = "1.8.0"


[workspace.dependencies.sqlx]
version = "0.7.4"
default-features = false
features = [
  "runtime-tokio",
  "tls-rustls",
  "macros",
  "postgres",
  "chrono",
  "time",
  "migrate",
  "json",
]

[workspace.dependencies.serenity]
#version = "0.12.0-rc2"
version = "0.12.1"
# git = "https://github.com/serenity-rs/serenity"
# branch = "next"
default-features = false
features = [
  "builder",
  "cache",
  "temp_cache",
  "collector",
  "client",
  "framework",
  "http",
  "standard_framework",
  "gateway",
  "model",
  "utils",
  "rustls_backend",
  "unstable_discord_api",
  "voice",
]

[workspace.dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
version = "0.4.1"
features = ["driver", "serenity", "rustls", "receive", "builtin-queue"]

# To get additional codecs, you *must* add Symphonia yourself.
# This includes the default formats (MKV/WebM, Ogg, Wave) and codecs (FLAC, PCM, Vorbis)...
[workspace.dependencies.symphonia]
version = "0.5.4"
default-features = false
features = ["all"]

[workspace.dependencies.poise]
# version = "0.5.6"
# version = "0.5.5"
# path = "../poise"
git = "https://github.com/cycle-five/poise"
branch = "current"
# git = "https://github.com/serenity-rs/poise"
# branch = "serenity-next"
# path = "../../src/poise"
default-features = true
features = ["cache", "chrono", "handle_panics"]

[workspace.dependencies.tokio]
version = "1.36.0"
features = ["macros", "rt-multi-thread", "signal"]

[profile.release-with-debug]
inherits = "release"
debug = 1


[profile.release]
incremental = true
# Set this to 1 or 2 to get more useful backtraces in debugger.
# debug = 0

# [profile.dev]
# # Disabling debug info speeds up builds a bunch,
# # and we don't rely on it for debugging that much.
# debug = 0

[profile.dev.package]
# This speeds up `cargo xtask dist`.
miniz_oxide.opt-level = 3
