[package]
name = "parrot"
version = "1.6.0"
authors = ["Cycle Five <cycle.five@proton.me>", "aquelemiguel"]
edition = "2018"
description = "A Discord music bot built in Rust"
repository = "https://github.com/cycle-five/cracktunes"
license = "MIT"
keywords = ["discord", "music-bot", "rust"]

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.8.4"
rspotify = "0.11.7"
serde_json = "1.0.96"
url = "2.4.0"
serde = "1.0.164"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
sys-info = "0.9.1"
chrono = "0.4.26"

[dependencies.songbird]
version = "0.3.2"
features = ["builtin-queue", "yt-dlp"]

# [dependencies.serenity]
# version = "0.11.5"
# default-features = false
# features = [
#   "builder",
#   "cache",
#   "collector",
#   "client",
#   "gateway",
#   "model",
#   "utils",
#   "rustls_backend",
#   "unstable_discord_api",
#   "voice",
# ]

[dependencies.poise]
version = "0.5.5"

[dependencies.tokio]
version = "1.28.2"
features = ["macros", "rt-multi-thread"]
