[package]
name = "cracktunes"
version = "0.2.5"
authors = ["Cycle Five <cycle.five@proton.me>", "aquelemiguel"]
edition = "2018"
description = "A Discord music bot built on Rust and Crack."
repository = "https://github.com/cycle-five/cracktunes"
license = "MIT"
keywords = ["discord", "music-bot", "rust"]

[features]
# default = ["shuttle"]
default = []
shuttle = []

[dependencies]
time = {version = "0.3.23", default-features = false, features = ["serde"]}
audiopus = "0.3.0-rc.0"
ctrlc = "3.4.0"
chatgpt_rs = "1.1.13"
colored = "2.0.4"
dotenv = "0.15.0"
lazy_static = "1.4.0"
lyric_finder = "0.1.3"
once_cell = "1.18.0"
rand = "0.8.5"
regex = "1.9.1"
ipinfo = "2.1.0"
serde_json = "1.0.104"
url = "2.4.0"
sha1 = "0.10.5"
serde = { version = "1.0.177", features = ["derive", "rc"] }
serde_stream = { version = "1.0.1", features = ["tokio"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
sys-info = "0.9.1"
prometheus = {version = "0.13.3", features = ["process"]}
config-file = {version="0.2.3", features = ["json"]}
reqwest = {version = "0.11.18", features = ["json"]}
anyhow = "1.0.72"
warp = "0.3.5"
whois-rust = "1.5.1"

[dependencies.rspotify]
git = "https://github.com/cycle-five/rspotify"
branch = "no-oldtime"

[dependencies.songbird]
version = "0.3.2"
features = [
  "driver-core",
  "driver",
  "rustls",
  "serenity",
  "builtin-queue",
  "yt-dlp",
  "audiopus",
]

[dependencies.serenity]
version = "0.11.6"
default-features = false
features = [
  "builder",
  "cache",
  "collector",
  "client",
  "gateway",
  "temp_cache",
  "model",
  "utils",
  "rustls_backend",
  "unstable_discord_api",
  "voice",
]

[dependencies.poise]
version = "0.5.5"
default-features = true

[dependencies.tokio]
version = "1.29.0"
features = ["macros", "rt-multi-thread", "signal"]

[dependencies.ffprobe]
git = "https://github.com/cycle-five/ffprobe-rs"