[workspace]
members = ["cracktunes", "crack-core", "crack-osint", "crack-gpt"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Cycle Five <cycle.five@proton.me>"]

[workspace.dependencies]
crack-core = { path = "crack-core", default-features = true, version = "0.3.5" }
crack-osint = { path = "crack-osint", default-features = true, version = "0.1" }
crack-gpt = { path = "crack-gpt", default-features = true, version = "0.1" }

reqwest = { version = "0.12.4", default-features = false, features = [
  "blocking",
  "json",
  "multipart",
  "rustls-tls",
] }
tracing = "0.1.40"


[workspace.dependencies.sqlx]
version = "0.7.4"
default-features = false
features = [
  "runtime-tokio-rustls",
  "tls-rustls",
  "macros",
  "postgres",
  "chrono",
  "migrate",
  "json",
]

[workspace.dependencies.serenity]
# version = "0.12.1"
path = "/home/lothrop/src/serenity"
default-features = false
features = [
  "builder",
  "cache",
  "temp_cache",
  "collector",
  "client",
  "framework",
  "http",
  "gateway",
  "model",
  "utils",
  "rustls_backend",
  "unstable_discord_api",
  "voice",
]

[workspace.dependencies.songbird]
# git = "https://github.com/serenity-rs/songbird"
# branch = "current"
path = "/home/lothrop/src/songbird"
version = "0.4.1"
features = ["driver", "serenity", "rustls", "receive", "builtin-queue"]

# To get additional codecs, you *must* add Symphonia yourself.
# This includes the default formats (MKV/WebM, Ogg, Wave) and codecs (FLAC, PCM, Vorbis)...
[workspace.dependencies.symphonia]
version = "0.5.4"
default-features = false
features = ["all", "opt-simd", "all-codecs", "all-formats"]

[workspace.dependencies.symphonia-metadata]
version = "0.5.4"
default-features = false
features = ["all"]

[workspace.dependencies.poise]
git = "https://github.com/cycle-five/poise"
branch = "current"
default-features = true
features = ["cache", "chrono", "handle_panics"]

[workspace.dependencies.tokio]
version = "1.37.0"
features = ["macros", "rt-multi-thread", "signal"]
# features = ["full"]

[profile.release-with-debug]
inherits = "release"
debug = 1

[profile.release]
incremental = true
# Set this to 1 or 2 to get more useful backtraces in debugger.
debug = 0
