# These settings will override the settings for all guilds
# only use them if you excplicitly want that.
# video_status_poll_interval = 120
# sys_log_channel_id = 0
# global_authorized_users = [ ]
# default_prefix = "r!"
owners = [ ]
database_url = "sqlite://./data/crackedmusic.db"

[[cam_kick]]
cammed_down_timeout = 0
guild_id = 0
channel_id = 0
dc_message = "You have been violated in voice channel for not having a camera on."
send_msg_deafen = false
send_msg_mute = false
send_msg_dc = false

[[guild_settings_map]]
guild_id = 0
prefix = "m/"
prefix_up = "M/"
authorized_users = [  ]
allow_all_domains = true
allowed_domains = [ "youtube.com" ]
banned_domains = [ ]
autopause = false
self_deafen = true
volume = 1.0
timeout = 0
[guild_settings_map.welcome_settings]
message = "Welcome to the server, {user}!"
channel_id = 0
auto_role = 0

[[guild_cache]]
