video_status_poll_interval = 120
sys_log_channel_id = 0
authorized_users = [ ]
self_deafen = true
volume = 1.0
prefix = "r!"

[[cam_kick]]
cammed_down_timeout = 0
guild_id = 0
channel_id = 0
dc_message = "You have been disconnected from the voice channel for not having a camera on."

[[guild_settings_map]]
guild_id = 0
authorized_users = [  ]
allowed_domains = [ "youtube.com" ]
banned_domains = [ ]
autopause = false
self_deafen = true
volume = 0.3
timeout = 0
[guild_settings_map.welcome_settings]
message = "Welcome to the server, {user}!"
channel_id = 0
autorole = 0

[[guild_cache]]
