# These settings will override the settings for all guilds
# only use them if you excplicitly want that.
# video_status_poll_interval = 120
# sys_log_channel_id = 0
# volume = 0.1
# prefix = "r!"
# owners = [ ]
database_url = "postgresql://postgres:mysecretpassword@crack_postgres:5432/postgres"
prefix = "t!"
