[workspace]
members = ["cargo:crack-cli"]

# Config for 'cargo dist'
[dist]
allow-dirty = ["ci"]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.21.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false
# Where to host releases
hosting = "github"
custom-success-message = "Be of Mæth and malinger not with Commies!"
# Run on latest ubuntu
[dist.github-custom-runners]
x86_64-unknown-linux-gnu = "ubuntu-latest"

[[dist.extra-artifacts]]
artifacts = ["data.tar"]
build = ["tar", "-cf", "data.tar", "data"]
