services:
  crack_postgres:
    container_name: crack_postgres
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGUSER=${POSTGRES_USER:-postgres}
      - PGPASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - PGDATABASE=${POSTGRES_DB:-postgres}
      - PGPORT=${PUB_PORT:-5432}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${PUB_PORT:-5432}:5432"
    expose:
      - "${PUB_PORT:-5432}"
    restart: always
  cracktunes:
    container_name: cracktunes
    image: cyclefive/cracktunes:dev
    volumes:
      - crack_data:/data:rw
      - ./.env:/home/cyclefive/app/.env:rw
      - ./cracktunes.toml:/home/cyclefive/app/cracktunes.toml:rw
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@crack_postgres:5432/postgres
      #- PUID=1001
      #- PGID=1001
    links:
      - crack_postgres
    ports:
      - "127.0.0.1:8833:8833"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL:-a@b.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW:-password}
    ports:
      - "127.0.0.1:5050:80"
    restart: always
volumes:
  pgdata:
    external: true
  crack_data:
    external: true
