version: '2'
services:
  crack_postgres:
    container_name: crack_postgres
    image: postgres:latest
    volumes:
      - /data/postgres:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}
    ports:
      - "127.0.0.1:${PGPORT}:${PGPORT}"
    restart: always
  cracktunes:
    container_name: cracktunes
    image: cyclefive/cracktunes:dev
    volumes:
      - "/data:/data"
      - "./.env:/app/.env"
      - "./cracktunes.toml:/app/cracktunes.toml"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@crack_postgres:${PGPORT}/postgres
    links:
      - crack_postgres
    ports:
      - "127.0.0.1:8000:8000"
