version: '2'
services:
  crack_postgres:
    container_name: crack_postgres
    image: postgres:latest
    volumes:
      - "/data/pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGPORT=${PGPORT}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${PGPORT}:${PGPORT}"
    restart: always
  cracktunes:
    container_name: cracktunes
    image: cyclefive/cracktunes:dev
    volumes:
      - /data/crack_data:/data:rw
      - ./.env:/app/.env:rw
      - ./cracktunes.toml:/app/cracktunes.toml:rw
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@crack_postgres:${PGPORT}/postgres
      #- PUID=1001
      #- PGID=1001
    links:
      - crack_postgres
    ports:
      - "127.0.0.1:8000:8000"
# volumes:
#   pgdata:
#   crack_data: