services:
  crack-postgres:
    container_name: crack-postgres
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - PGUSER=${POSTGRES_USER:-postgres}
      - PGPASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mysecretpassword}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - PGDATABASE=${POSTGRES_DB:-postgres}
      - PGPORT=${PUB_PORT:-5432}
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${PUB_PORT:-5432}:5432"
    expose:
      - "${PUB_PORT:-5432}"
    restart: always
  crack-voting:
    container_name: crack-voting
    image: cyclefive/crack-voting:dev
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@crack-postgres:5432/postgres
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-test_secret}
    links:
      - crack-postgres
    ports:
      - "3030:3030"
  cracktunes:
    container_name: cracktunes
    image: cyclefive/cracktunes:dev-debian
    volumes:
      - crack_data:/data:rw
      - ./.env:/app/.env:rw
      - ./cracktunes.toml:/app/cracktunes.toml:rw
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@crack-postgres:5432/postgres
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY:-test_key}
    links:
      - crack-postgres
    ports:
      - "127.0.0.1:8833:8833"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL:-a@b.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW:-password}
    ports:
      - "127.0.0.1:5050:80"
    restart: always
# For IPv6 address rotating to escape YouTube blocking.
networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB9::/112
          gateway: 2001:0DB9::1
volumes:
  pgdata:
    external: true
  crack_data:
    external: true
