[package]
name = "crack-gpt"
version = "0.1.1"
edition = "2021"

[dependencies]
chatgpt_rs = "1.2"
url = "2.4"
tracing = "0.1"
tokio = { version = "1.35.0", features = ["rt-multi-thread", "macros"] }
