[package]
name = "crack-gpt"
version = "0.1.1"
edition = "2021"
authors = ["Cycle Five <cycle.five@proton.me>"]
publish = true
license = "MIT"
description = "GPT module for Cracktunes."
keywords = ["music", "discord", "bot", "crack", "tunes"]
categories = ["multimedia::audio"]
homepage = "https://cracktun.es/"
repository = "https://git.sr.ht/~cycle-five/cracktunes"


[dependencies]
chatgpt_rs = "1.2"
url = "2.5"
tracing = "0.1"
tokio = { version = "1.36", features = ["rt-multi-thread", "macros"] }
