[package]
name = "crack-gpt"
version = "0.1.2"
edition = "2021"
authors = ["Cycle Five <cycle.five@proton.me>"]
publish = true
license = "MIT"
description = "GPT module for Cracktunes."
keywords = ["music", "discord", "bot", "crack", "tunes"]
categories = ["multimedia::audio"]
homepage = "https://cracktun.es/"
repository = "https://git.sr.ht/~cycle-five/cracktunes"


[dependencies]
chatgpt_rs = { git = "https://github.com/cycle-five/chatgpt_rs", branch = "master", version = "1.2.4" }
async-openai = "0.21.0"
url = "2.5"
ctor = "0.2.8"
tracing = { workspace = true }
tokio = { workspace = true }
