[package]
authors = ["Cycle Five <cycle.five@proton.me>"]
name = "cracktunes"
version = "0.3.2"
description = "Cracktunes is a hassle-free, highly performant, host-it-yourself, cracking smoking, discord-music-bot."
publish = true
edition = "2021"
license = "MIT"
keywords = ["music", "discord", "bot", "crack", "tunes"]
categories = ["multimedia::audio"]
homepage = "https://cracktun.es/"
repository = "https://git.sr.ht/~cycle-five/cracktunes"

[features]
default = ["db", "crack-gpt", "crack-osint", "crack-tracing"]
db = ["crack-core/sqlx", "sqlx"]
crack-gpt = ["dep:crack-gpt"]
crack-osint = ["dep:crack-osint"]

crack-tracing = ["tracing-subscriber", "tracing-futures"]
crack-metrics = ["prometheus", "warp"]
crack-telemetry = [
    "opentelemetry",
    "opentelemetry-otlp",
    "opentelemetry-semantic-conventions",
    "tracing-opentelemetry",
    "tracing-bunyan-formatter",
    "tonic",
    "warp",
]

[dependencies]
# core
crack-core = { workspace = true, optional = false }
# modules, each should be optional
crack-osint = { workspace = true, optional = true }
crack-gpt = { workspace = true, optional = true }

# Core's dependencies
poise = { workspace = true }
tokio = { workspace = true }
songbird = { workspace = true }
symphonia = { workspace = true }
tungstenite = { workspace = true }
async-tungstenite = { workspace = true }
async-trait = { version = "0.1" }
mockall = { version = "0.12" }
config-file = { version = "0.2", features = ["json"] }
dotenv = "0.15"
colored = "2.1"
# Figure this one out better
sqlx = { workspace = true, optional = true }

# crack-telemetry
opentelemetry = { version = "0.22", optional = true }
opentelemetry-otlp = { version = "0.15", features = [
    "logs",
    "metrics",
    "trace",
    "grpc-tonic",
], optional = true }
opentelemetry_sdk = { version = "0.22", features = [
    "rt-tokio",
], optional = true }
opentelemetry-semantic-conventions = { version = "0.14", optional = true }
tonic = { version = "0.11", optional = true }

tracing = { workspace = true }
tracing-opentelemetry = { version = "0.23.0", optional = true }
tracing-bunyan-formatter = { version = "0.3.9", optional = true }
tracing-appender = { version = "0.2", optional = true }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
], optional = true }
tracing-futures = { version = "0.2", optional = true }

# crack-metrics
prometheus = { version = "0.13", features = ["process"], optional = true }
warp = { version = "0.3", optional = true }

# # Is this even needed? What did I add it for?
# [dev-dependencies]
# async-tungstenite = "0.25"
# tungstenite = "0.21"
[dev-dependencies]
sqlx = { version = "0.7.4", features = ["runtime-async-std", "macros"] }
