[package]
name = "cracktunes"
version = "0.2.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["playlist", "crack-config"]
playlist = ["crack-core/sqlx", "sqlx"]


[dependencies]
crack-core = { workspace = true }
crack-config = { workspace = true, optional = true }
crack-osint = { workspace = true, optional = true }
crack-gpt = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
poise = { workspace = true }
tokio = { workspace = true }
songbird = { workspace = true }
symphonia = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tungstenite = { workspace = true }
async-tungstenite = { workspace = true }
async-trait = { version = "0.1" }
mockall = { version = "0.11" }
prometheus = { version = "0.13", features = ["process"] }
warp = "0.3"
config-file = { version = "0.2", features = ["json"] }
dotenv = "0.15"

[dev-dependencies]
tungstenite = "^0.20.1"
async-tungstenite = "^0.23.0"
