[package]
authors = ["Cycle Five <cycle.five@proton.me>"]
name = "cracktunes"
version = "0.3.0"
description = "Cracktunes is a hassle-free, highly performant, host-it-yourself, cracking smoking, discord-music-bot."
publish = true
edition = "2021"
license = "MIT"
keywords = ["music", "discord", "bot", "crack", "tunes"]
categories = ["multimedia::audio"]
homepage = "https://cracktun.es/"
repository = "https://git.sr.ht/~cycle-five/cracktunes"

[features]
default = ["playlist", "crack-gpt", "crack-osint"]
playlist = ["crack-core/sqlx", "sqlx"]
crack-gpt = ["dep:crack-gpt"]
crack-osint = ["dep:crack-osint"]
crack-telemetry = [
    "opentelemetry",
    "opentelemetry-otlp",
    "opentelemetry-semantic-conventions",
    "tracing-opentelemetry",
    "tracing-bunyan-formatter",
]
crack-metrics = ["prometheus"]

[dependencies]
opentelemetry = { version = "0.22", optional = true }
opentelemetry-otlp = { version = "0.15", features = [
    "logs",
    "metrics",
    "trace",
    "grpc-tonic",
], optional = true }
opentelemetry_sdk = { version = "0.22", features = [
    "rt-tokio",
], optional = true }
opentelemetry-semantic-conventions = { version = "0.14", optional = true }
tracing-opentelemetry = { version = "0.23.0", optional = true }
tracing-bunyan-formatter = { version = "0.3.9", optional = true }
prometheus = { version = "0.13", features = ["process"], optional = true }
crack-core = { workspace = true, optional = false }
crack-osint = { workspace = true, optional = true }
crack-gpt = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
poise = { workspace = true }
tokio = { workspace = true }
songbird = { workspace = true }
symphonia = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-futures = { workspace = true }
# tracing-bunyan-formatter = { workspace = true }
# opentelemetry = { workspace = true, optional = true }
# tracing-opentelemetry = { workspace = true, optional = true }
# opentelemetry_sdk = { workspace = true, optional = true }
# opentelemetry-otlp = { workspace = true, optional = true }
# opentelemetry-semantic-conventions = { workspace = true, optional = true
tungstenite = { workspace = true }
async-tungstenite = { workspace = true }
async-trait = { version = "0.1" }
mockall = { version = "0.12" }
warp = "0.3"
config-file = { version = "0.2", features = ["json"] }
dotenv = "0.15"
colored = "2.1"

[dev-dependencies]
async-tungstenite = "0.25"
tungstenite = "0.21"
