{
 "title": "PostgreSQL Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Database Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() as time, pg_database_size('postgres') as \"Database Size\""
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() as time, COUNT(*) as \"Active Connections\" FROM pg_stat_activity"
    }
   ]
  },
  {
   "title": "Database Sizes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT datname as \"Database\", round(pg_database_size(datname)/1024/1024, 2) as \"Size (MB)\" FROM pg_database;"
    }
   ]
  }
 ]
}