pub mod admin;
#[cfg(feature = "crack-gpt")]
pub mod chatgpt;
#[cfg(feature = "crack-osint")]
pub mod crack_osint;
pub mod music;
pub mod ping;
pub mod playlist;
pub mod settings;
pub mod version;

pub use admin::*;
#[cfg(feature = "crack-gpt")]
pub use chatgpt::*;
#[cfg(feature = "crack-osint")]
pub use crack_osint::*;
pub use music::*;
pub use ping::*;
pub use playlist::playlist;
pub use settings::*;
pub use version::*;
