name: Main Workflow

on:
  workflow_call:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["nightly", "stable"]
        cache-key: [""]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      # redis:
      #   image: redis:latest
      #   ports:
      #     - 6379/tcp

    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: "Install Rust"
        run: |
          rustup toolchain install ${{ matrix.rust-version }} --profile minimal --no-self-update
          rustup default ${{ matrix.rust-version }}
          rustup update
        shell: bash

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.cache-key }}

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Migrate database
        env:
          DATABASE_URL: postgresql://postgres:mysecretpassword@postgres:5432/postgres
          PG_USER: postgres
          PG_PASSWORD: mysecretpassword
        run: |
          sqlx database create
          sqlx migrate run --source migrations/
          cargo sqlx prepare --workspace -- --tests

      - name: Run Unit Tests
        if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')
        run: cargo test

      - name: Run Release Unit Tests
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: cargo test --release --locked

      # - name: Build Binary
      #   if: github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/')
      #   run: cargo build --locked

      - name: Build Release Binary
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        run: cargo build --release --locked
