name: CI Workflow

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref == 'refs/heads/master')
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  lint:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.ref == 'refs/heads/master')
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  docker:
    name: Docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [build, lint]
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  # dockerhub:
  #   name: Dockerhub
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  #   needs: [build, lint]
  #   uses: ./.github/workflows/dockerhub.yml
  #   secrets: inherit
