name: Docker Workflow

on:
  push:
    tags: ['v*.*.*']
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - 
        name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres
      - 
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: postgres
          password: mysecretpassword
          database: postgres
          port: 5432
        id: postgres
      - 
        name: Cache
        uses: Swatinem/rust-cache@v2
      - 
        name: Migrate database
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }} 
        run: |
          sqlx database create
          sqlx migrate run --source migrations/
          cargo sqlx prepare --workspace
      - 
        name: Build Docker Image
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
        run: docker build . -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
  push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_call' && github.event.inputs.trigger == 'build')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - 
        name: Cache
        uses: Swatinem/rust-cache@v2
      - 
        name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres
      - 
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: postgres
          password: mysecretpassword
          database: postgres
          port: 5432
        id: postgres
      -
        name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract Git Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - 
        name: Migrate database
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}
          PG_USER: postgres
          PG_PASSWORD: mysecretpassword
        run: |
          sqlx database create
          sqlx migrate run --source migrations/
          cargo sqlx prepare --workspace
      - 
        name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
